version: '3.8'
services:
  frankenphp:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
      - APP_KEY=base64:8dQ7xw/kM9EYMV4cUkzKgET8jF4P0M0TOmmqN05RN2w=
      - APP_NAME=Wave
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
