version: '3.8'

services:
  app:
    image: spazacloud-wave:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - laravel-network
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

networks:
  laravel-network:
    driver: overlay
